import Foundation

public struct SwiftEnumGenerator {
    public struct Configuration: Sendable {
        public let enumName: String
        public let accessLevel: String

        public init(enumName: String = "L10n", accessLevel: String = "internal") {
            self.enumName = enumName
            self.accessLevel = accessLevel
        }
    }

    public init() {}

    public func generate(catalog: StringCatalog, configuration: Configuration = .init()) -> String {
        let accessLevel = configuration.accessLevel == "public" ? "public " : ""
        let members = makeMembers(from: catalog.entries)
        let memberLines = members.map(\.rendered).joined(separator: "\n\n")
        let tr = """
        \(accessLevel)static func tr(_ key: String) -> String {
                NSLocalizedString(key, comment: "")
            }

        \(accessLevel)static func tr(_ key: String, _ args: CVarArg...) -> String {
                let format = tr(key)
                return String(format: format, locale: Locale.current, arguments: args)
            }
        """

        return """
        // Generated by EVLocalizable. Do not edit.
        import Foundation

        \(accessLevel)enum \(configuration.enumName): Sendable {
        \(memberLines)

        \(tr)
        }
        """
    }

    private func makeMembers(from entries: [StringCatalog.Entry]) -> [(key: String, rendered: String)] {
        var usedNames = Set<String>()
        return entries.map { entry in
            let baseName = Self.swiftIdentifier(for: entry.key)
            let uniqueName = Self.makeUnique(baseName: baseName, usedNames: &usedNames)
            let arguments = FormatSpecifierParser.parse(entry.developmentValue ?? "")
            return (
                key: entry.key,
                rendered: renderMember(key: entry.key, name: uniqueName, arguments: arguments)
            )
        }
    }

    private func renderMember(key: String, name: String, arguments: [FormatArgument]) -> String {
        let keyConstant = "\(name)Key"

        if arguments.isEmpty {
            return """
                static let \(keyConstant) = \(quoted(key))
                static var \(name): String { tr(\(keyConstant)) }
            """
        }

        let parameters = arguments.map { argument in
            "_ \(argument.name): \(argument.swiftType)"
        }.joined(separator: ", ")

        let passedArguments = arguments.map(\.name).joined(separator: ", ")

        return """
            static let \(keyConstant) = \(quoted(key))
            static func \(name)(\(parameters)) -> String { tr(\(keyConstant), \(passedArguments)) }
        """
    }

    private static func makeUnique(baseName: String, usedNames: inout Set<String>) -> String {
        guard usedNames.contains(baseName) else {
            usedNames.insert(baseName)
            return baseName
        }

        var index = 2
        while usedNames.contains("\(baseName)\(index)") {
            index += 1
        }

        let uniqueName = "\(baseName)\(index)"
        usedNames.insert(uniqueName)
        return uniqueName
    }

    private static func swiftIdentifier(for key: String) -> String {
        let parts = key
            .split(whereSeparator: { !$0.isLetter && !$0.isNumber })
            .map(String.init)
            .filter { !$0.isEmpty }

        let rawName: String
        if let first = parts.first {
            let head = first.prefix(1).lowercased() + first.dropFirst()
            let tail = parts.dropFirst().map { $0.prefix(1).uppercased() + $0.dropFirst().lowercased() }
            rawName = ([head] + tail).joined()
        } else {
            rawName = "value"
        }

        let normalized = rawName.unicodeScalars.map { scalar -> String in
            CharacterSet.alphanumerics.contains(scalar) ? String(scalar) : "_"
        }.joined()

        let prefixed = normalized.first?.isNumber == true ? "_\(normalized)" : normalized
        return reservedKeywords.contains(prefixed) ? "`\(prefixed)`" : prefixed
    }

    private func quoted(_ value: String) -> String {
        let escaped = value
            .replacingOccurrences(of: "\\", with: "\\\\")
            .replacingOccurrences(of: "\"", with: "\\\"")
        return "\"\(escaped)\""
    }
}

private struct FormatArgument {
    let name: String
    let swiftType: String
}

private enum FormatSpecifierParser {
    static func parse(_ value: String) -> [FormatArgument] {
        let pattern = #"%(?:\d+\$)?(?:[-+# 0])*(?:\d+|\*)?(?:\.(?:\d+|\*))?(?:hh|h|ll|l|L|z|t|j)?[@dDuUxXoOfFeEgGcCsSpaA]"#
        guard let regex = try? NSRegularExpression(pattern: pattern) else {
            return []
        }

        let range = NSRange(value.startIndex..<value.endIndex, in: value)
        let matches = regex.matches(in: value, range: range)
        var index = 1
        return matches.compactMap { match in
            guard let tokenRange = Range(match.range, in: value) else {
                return nil
            }

            let token = String(value[tokenRange])
            guard token != "%%" else { return nil }

            let specifier = token.last ?? "@"
            let swiftType = swiftType(for: specifier)
            defer { index += 1 }
            return FormatArgument(name: "arg\(index)", swiftType: swiftType)
        }
    }

    private static func swiftType(for specifier: Character) -> String {
        switch specifier {
        case "@", "s", "S":
            return "String"
        case "d", "D", "i", "u", "U", "x", "X", "o", "O", "c", "C":
            return "Int"
        case "f", "F", "e", "E", "g", "G", "a", "A":
            return "Double"
        case "p":
            return "UnsafeRawPointer"
        default:
            return "CVarArg"
        }
    }
}

private let reservedKeywords: Set<String> = [
    "associatedtype", "class", "deinit", "enum", "extension", "fileprivate",
    "func", "import", "init", "inout", "internal", "let", "open", "operator",
    "private", "protocol", "public", "rethrows", "static", "struct", "subscript",
    "typealias", "var", "break", "case", "catch", "continue", "default", "defer",
    "do", "else", "fallthrough", "for", "guard", "if", "in", "repeat", "return",
    "switch", "throw", "where", "while", "as", "Any", "false", "is", "nil",
    "self", "Self", "super", "throws", "true", "try"
]
