import Foundation

public struct SwiftEnumGenerator {
    public struct Configuration: Sendable {
        public let enumName: String
        public let accessLevel: String

        public init(enumName: String = "Localizable", accessLevel: String = "internal") {
            self.enumName = enumName
            self.accessLevel = accessLevel
        }
    }

    public init() {}

    public func generate(catalog: StringCatalog, configuration: Configuration = .init()) -> String {
        let cases = makeCases(from: catalog.keys)
        let accessLevel = configuration.accessLevel == "public" ? "public " : ""
        let caseLines = cases.map { item in
            "    case \(item.caseName) = \(quoted(item.key))"
        }.joined(separator: "\n")

        return """
        // Generated by EVLocalizable. Do not edit.
        import Foundation

        \(accessLevel)enum \(configuration.enumName): String, CaseIterable, Sendable {
        \(caseLines)

        \(accessLevel)var key: String {
                rawValue
            }

        \(accessLevel)var localized: String {
                NSLocalizedString(rawValue, comment: "")
            }
        }
        """
    }

    private func makeCases(from keys: [String]) -> [(key: String, caseName: String)] {
        var usedNames = Set<String>()
        return keys.map { key in
            let baseName = Self.swiftIdentifier(for: key)
            let uniqueName = Self.makeUnique(baseName: baseName, usedNames: &usedNames)
            return (key: key, caseName: uniqueName)
        }
    }

    private static func makeUnique(baseName: String, usedNames: inout Set<String>) -> String {
        guard usedNames.contains(baseName) else {
            usedNames.insert(baseName)
            return baseName
        }

        var index = 2
        while usedNames.contains("\(baseName)\(index)") {
            index += 1
        }

        let uniqueName = "\(baseName)\(index)"
        usedNames.insert(uniqueName)
        return uniqueName
    }

    private static func swiftIdentifier(for key: String) -> String {
        let parts = key
            .split(whereSeparator: { !$0.isLetter && !$0.isNumber })
            .map(String.init)
            .filter { !$0.isEmpty }

        let rawName: String
        if let first = parts.first {
            let head = first.prefix(1).lowercased() + first.dropFirst()
            let tail = parts.dropFirst().map { $0.prefix(1).uppercased() + $0.dropFirst().lowercased() }
            rawName = ([head] + tail).joined()
        } else {
            rawName = "value"
        }

        let normalized = rawName.unicodeScalars.map { scalar -> String in
            CharacterSet.alphanumerics.contains(scalar) ? String(scalar) : "_"
        }.joined()

        let prefixed = normalized.first?.isNumber == true ? "_\(normalized)" : normalized
        return reservedKeywords.contains(prefixed) ? "`\(prefixed)`" : prefixed
    }

    private func quoted(_ value: String) -> String {
        let escaped = value
            .replacingOccurrences(of: "\\", with: "\\\\")
            .replacingOccurrences(of: "\"", with: "\\\"")
        return "\"\(escaped)\""
    }
}

private let reservedKeywords: Set<String> = [
    "associatedtype", "class", "deinit", "enum", "extension", "fileprivate",
    "func", "import", "init", "inout", "internal", "let", "open", "operator",
    "private", "protocol", "public", "rethrows", "static", "struct", "subscript",
    "typealias", "var", "break", "case", "catch", "continue", "default", "defer",
    "do", "else", "fallthrough", "for", "guard", "if", "in", "repeat", "return",
    "switch", "throw", "where", "while", "as", "Any", "false", "is", "nil",
    "self", "Self", "super", "throws", "true", "try"
]
